/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiClassify426
 */
interface ApiClassify426 {
  message?: string;
}

export class ApiClassify426Error extends ApiError<ApiClassify426> {}
