/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiLemmatize426
 */
interface ApiLemmatize426 {
  message?: string;
}

export class ApiLemmatize426Error extends ApiError<ApiLemmatize426> {}
