/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiMorph426
 */
interface ApiMorph426 {
  message?: string;
}

export class ApiMorph426Error extends ApiError<ApiMorph426> {}
