/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiPostag426
 */
interface ApiPostag426 {
  message?: string;
}

export class ApiPostag426Error extends ApiError<ApiPostag426> {}
