/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiStemmer426
 */
interface ApiStemmer426 {
  message?: string;
}

export class ApiStemmer426Error extends ApiError<ApiStemmer426> {}
