/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of M426
 */
interface M426 {
  message?: string;
}

export class M426Error extends ApiError<M426> {}
