/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Input9, input9Schema } from './input9';

export interface ApiImagecaptionRequest {
  input: Input9;
}

export const apiImagecaptionRequestSchema: Schema<ApiImagecaptionRequest> = object(
  { input: ['input', lazy(() => input9Schema)] }
);
