/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ApiImagecaptionResponse {
  generatedCaption: string;
}

export const apiImagecaptionResponseSchema: Schema<ApiImagecaptionResponse> = object(
  { generatedCaption: ['generated_caption', string()] }
);
