/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ApiNerResponse {
  /** Entity group inferred. */
  entityGroup: string;
  /** Corresponding word */
  word: string;
  /** Start position of the entity in the given input. */
  start: string;
  /** Start position of the entity in the given input. */
  end: string;
}

export const apiNerResponseSchema: Schema<ApiNerResponse> = object({
  entityGroup: ['entity_group', string()],
  word: ['word', string()],
  start: ['start', string()],
  end: ['end', string()],
});
