/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ApiQuestionResponse {
  /** Answer to the question. */
  answer: string;
}

export const apiQuestionResponseSchema: Schema<ApiQuestionResponse> = object({
  answer: ['answer', string()],
});
