/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface ApiQaResponse {
  /** What is the confident score of the answer */
  score: number;
  /** Start position of the answer in the context */
  start: number;
  /** End position of the answer in the context */
  end: number;
  /** Answer to the question. */
  answer: string;
}

export const apiQaResponseSchema: Schema<ApiQaResponse> = object({
  score: ['score', number()],
  start: ['start', number()],
  end: ['end', number()],
  answer: ['answer', string()],
});
