/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Input10, input10Schema } from './input10';

export interface ApiQuestionRequest {
  input: Input10;
}

export const apiQuestionRequestSchema: Schema<ApiQuestionRequest> = object({
  input: ['input', lazy(() => input10Schema)],
});
