/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiSummaryResponse {
  summary?: string;
}

export const apiSummaryResponseSchema: Schema<ApiSummaryResponse> = object({
  summary: ['summary', optional(string())],
});
