/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ApiTranslateResponse {
  generatedText?: string;
}

export const apiTranslateResponseSchema: Schema<ApiTranslateResponse> = object({
  generatedText: ['generated_text', optional(string())],
});
