/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors1 {
  msg?: string;
  param?: string;
  location?: string;
}

export const errors1Schema: Schema<Errors1> = object({
  msg: ['msg', optional(string())],
  param: ['param', optional(string())],
  location: ['location', optional(string())],
});
