/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Direct Text Input */
export interface Input {
  /** Word or sentence or a paragraph. Special characters will not be stripped. */
  text: string;
  /** Allowed language code. Refer Allowed languages section. */
  lang: string;
}

export const inputSchema: Schema<Input> = object({
  text: ['text', string()],
  lang: ['lang', string()],
});
