/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema';

export interface Input3 {
  /** URL where the content is hosted. */
  url: string;
  /** Allowed language code. Refer Allowed languages section. */
  lang: string;
  /** Allowed values or html or text. If html is specified all html tags and special characters will be stripped before processing. */
  contentType: string;
  /** Labels to classify */
  labels: unknown[];
}

export const input3Schema: Schema<Input3> = object({
  url: ['url', string()],
  lang: ['lang', string()],
  contentType: ['contentType', string()],
  labels: ['labels', array(unknown())],
});
