/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Text for processing will be read from the given URL. Only HTML pages or text pages will be processed at this time. */
export interface Input1 {
  /** URL where the content is hosted. */
  url?: string;
  /** Allowed language code. Refer Allowed languages section. */
  lang?: string;
  /** Allowed values or html or text. If html is specified all html tags and special characters will be stripped before processing. */
  contentType?: string;
}

export const input1Schema: Schema<Input1> = object({
  url: ['url', optional(string())],
  lang: ['lang', optional(string())],
  contentType: ['contentType', optional(string())],
});
