/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string, unknown } from '../schema';

export interface Input2 {
  /** Word or sentence or a paragraph. Special characters will not be stripped. */
  context: string;
  /** Allowed language code. Refer Allowed languages section. */
  lang: string;
  /** Labels to classify */
  labels: unknown[];
}

export const input2Schema: Schema<Input2> = object({
  context: ['context', string()],
  lang: ['lang', string()],
  labels: ['labels', array(unknown())],
});
