/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Input10 {
  /** Question to be answered from the context loaded in memory */
  question: string;
  /** Language of the question */
  lang: string;
}

export const input10Schema: Schema<Input10> = object({
  question: ['question', string()],
  lang: ['lang', string()],
});
