/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface OrignalString {
  morphAttr?: string[];
}

export const orignalStringSchema: Schema<OrignalString> = object({
  morphAttr: ['morph_attr', optional(array(string()))],
});
