/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Responsepo {
  orginalText?: string;
  postag?: string;
}

export const responsepoSchema: Schema<Responsepo> = object({
  orginalText: ['orginalText', optional(string())],
  postag: ['postag', optional(string())],
});
