/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Responseclassify {
  labels?: string[];
  scores?: number[];
}

export const responseclassifySchema: Schema<Responseclassify> = object({
  labels: ['labels', optional(array(string()))],
  scores: ['scores', optional(array(number()))],
});
