/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Responselemma {
  orginalText?: string;
  lemmatized?: string;
}

export const responselemmaSchema: Schema<Responselemma> = object({
  orginalText: ['orginalText', optional(string())],
  lemmatized: ['lemmatized', optional(string())],
});
