/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Responsestem {
  orginalText?: string;
  stem?: string;
}

export const responsestemSchema: Schema<Responsestem> = object({
  orginalText: ['orginalText', optional(string())],
  stem: ['stem', optional(string())],
});
