/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { OrignalString, orignalStringSchema } from './orignalString';

export interface Responsemorph {
  orignalString?: OrignalString;
}

export const responsemorphSchema: Schema<Responsemorph> = object({
  orignalString: ['orignalString', optional(lazy(() => orignalStringSchema))],
});
