/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Input2, input2Schema } from './input2';

export interface TextInputClassify {
  input?: Input2;
}

export const textInputClassifySchema: Schema<TextInputClassify> = object({
  input: ['input', optional(lazy(() => input2Schema))],
});
