/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Input4, input4Schema } from './input4';

export interface TextInputTamil {
  input: Input4;
}

export const textInputTamilSchema: Schema<TextInputTamil> = object({
  input: ['input', lazy(() => input4Schema)],
});
