/**
 * FirstLanguage APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Input3, input3Schema } from './input3';

export interface URLInputClassify {
  input?: Input3;
}

export const uRLInputClassifySchema: Schema<URLInputClassify> = object({
  input: ['input', optional(lazy(() => input3Schema))],
});
